SOURCES_DIR_ROOT=src
PDF_DIR_ROOT=pdf
WEBSITE_DIR_ROOT=website

WEBSITE_OTHER_PAGES_DIR=pages
WEBSITE_OTHER_PAGES_DIR_ROOT=${WEBSITE_DIR_ROOT}/${WEBSITE_OTHER_PAGES_DIR}

WEBSITE_CONTENT_DIR=content/pages
WEBSITE_CONTENT_DIR_ROOT=${WEBSITE_DIR_ROOT}/${WEBSITE_CONTENT_DIR}

WEBSITE_OUTPUT_DIR=output
WEBSITE_OUTPUT_DIR_ROOT=${WEBSITE_DIR_ROOT}/${WEBSITE_OUTPUT}

WEBSITE_GHPAGES_DIR=ghpages
WEBSITE_GHPAGES_DIR_ROOT=${WEBSITE_DIR_ROOT}/${WEBSITE_GHPAGES_DIR}
